# This is a basic workflow to help you get started with Actions

name: kernel build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  # pull_request:
  #   types:
  #     - closed
  schedule:
    - cron:  '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Kernel Source Code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Dependency
        run: |
          sudo apt update
          sudo apt install -y build-essential gcc-riscv64-linux-gnu flex bison libssl-dev libelf-dev dwarves
          riscv64-linux-gnu-gcc -v
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          make mrproper
          make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- openeuler_defconfig
          make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -j $(nproc)
          make ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- -j $(nproc)
          mkdir kernel_image
          cp arch/riscv/boot/Image kernel_image
      
      # Runs a set of commands using the runners shell
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: deploy
          FOLDER: kernel_image
